import React, { useState } from 'react';
import {
  Zap,
  TrendingDown,
  Clock,
  HelpCircle,
  CheckCircle2,
  ArrowRight,
  ShieldCheck,
  BrainCircuit,
  X,
  Sparkles,
  ChevronDown,
  ChevronUp,
  Cpu,
  Sliders,
  Layers,
  DoorOpen,
  Bus,
  Coffee
} from 'lucide-react';
import { AIAction, Zone, Gate, TransportHub } from '../types';
import { WhatIfAssistant } from './WhatIfAssistant';

interface ActionsScreenProps {
  actions: AIAction[];
  onSimulateAction: (actionId: string) => void;
  onApplyAction: (actionId: string) => void;
  zones?: Zone[];
  gates?: Gate[];
  transports?: TransportHub[];
  onOpenOptimizer?: () => void;
}

export const ActionsScreen: React.FC<ActionsScreenProps> = ({
  actions,
  onSimulateAction,
  onApplyAction,
  zones = [],
  gates = [],
  transports = [],
  onOpenOptimizer,
}) => {
  const [activeWhyAction, setActiveWhyAction] = useState<AIAction | null>(null);
  const [showWhatIf, setShowWhatIf] = useState<boolean>(false);

  return (
    <div
      id="mobile-actions-screen"
      className="w-full max-w-lg mx-auto flex flex-col gap-4 px-4 pt-3 pb-24 text-white"
    >
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
            <Zap className="w-5 h-5 text-blue-400" />
            AI Actions
          </h1>
          <p className="text-xs text-white/60 mt-0.5">
            Real-time algorithmic interventions generated by EventFlow
          </p>
        </div>
        <span className="text-[10px] font-mono text-purple-400 bg-purple-600/20 px-3 py-1 rounded-full border border-purple-500/30 font-bold">
          OR-TOOLS MILP
        </span>
      </div>

      {/* Prescriptive Optimizer Showcase Card */}
      {onOpenOptimizer && (
        <div
          id="prescriptive-optimizer-banner"
          className="bg-gradient-to-br from-purple-950/40 via-black/70 to-blue-950/30 border border-purple-500/40 rounded-2xl p-4 backdrop-blur-xl shadow-[0_0_25px_rgba(168,85,247,0.15)] flex flex-col gap-3"
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-xl bg-purple-600/30 border border-purple-500/40 flex items-center justify-center text-purple-300">
                <Cpu className="w-4 h-4" />
              </div>
              <div>
                <h2 className="text-xs font-bold text-white flex items-center gap-1.5">
                  <span>Prescriptive Constraint-Aware Optimizer</span>
                </h2>
                <span className="text-[10px] font-mono text-purple-300">
                  OR-Tools Bounded MILP Solver
                </span>
              </div>
            </div>
            <span className="text-[10px] font-mono font-bold bg-emerald-500/20 text-emerald-300 px-2 py-0.5 rounded-full border border-emerald-500/30">
              OPTIMAL (16ms)
            </span>
          </div>

          <p className="text-[11px] text-white/70 leading-relaxed">
            Solves bounded Mixed-Integer Linear Programming across <strong>Gate throughput</strong>, <strong>turnstile limits</strong>, <strong>walking distances (≤350m)</strong>, and <strong>shuttle fleet reserves (4/8)</strong> to prescribe ranked, mathematically feasible diversions.
          </p>

          <div className="grid grid-cols-4 gap-1.5 text-[10px] font-mono text-center">
            <div className="bg-white/5 p-1.5 rounded-lg border border-white/5 flex flex-col items-center justify-center">
              <DoorOpen className="w-3 h-3 text-amber-400 mb-0.5" />
              <span className="text-white/40 text-[9px] block">Turnstiles</span>
              <span className="text-amber-300 font-bold">≤85% Max</span>
            </div>
            <div className="bg-white/5 p-1.5 rounded-lg border border-white/5 flex flex-col items-center justify-center">
              <Sliders className="w-3 h-3 text-blue-400 mb-0.5" />
              <span className="text-white/40 text-[9px] block">Max Walk</span>
              <span className="text-blue-300 font-bold">≤350m</span>
            </div>
            <div className="bg-white/5 p-1.5 rounded-lg border border-white/5 flex flex-col items-center justify-center">
              <Bus className="w-3 h-3 text-emerald-400 mb-0.5" />
              <span className="text-white/40 text-[9px] block">Shuttles</span>
              <span className="text-emerald-300 font-bold">4 / 8 EV</span>
            </div>
            <div className="bg-white/5 p-1.5 rounded-lg border border-white/5 flex flex-col items-center justify-center">
              <Coffee className="w-3 h-3 text-purple-400 mb-0.5" />
              <span className="text-white/40 text-[9px] block">Lounge</span>
              <span className="text-purple-300 font-bold">400 Pax</span>
            </div>
          </div>

          <button
            id="btn-open-prescriptive-optimizer"
            onClick={onOpenOptimizer}
            className="w-full py-2.5 px-3 bg-purple-600 hover:bg-purple-500 text-white rounded-xl text-xs font-bold transition flex items-center justify-center gap-1.5 shadow-md shadow-purple-600/30 active:scale-98"
          >
            <Cpu className="w-3.5 h-3.5" />
            <span>Open Prescriptive Optimizer Console</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </button>
        </div>
      )}

      {/* AI What-If Decision Assistant Toggle & Box */}
      {zones.length > 0 && gates.length > 0 && (
        <div className="flex flex-col gap-2">
          <button
            id="btn-toggle-what-if-actions"
            onClick={() => setShowWhatIf(!showWhatIf)}
            className="w-full bg-blue-600/15 hover:bg-blue-600/25 border border-blue-500/30 p-3.5 rounded-2xl flex items-center justify-between transition active:scale-98 backdrop-blur-md"
          >
            <div className="flex items-center gap-2.5">
              <span className="p-1.5 rounded-xl bg-blue-600/30 text-blue-400">
                <Sparkles className="w-4 h-4 text-amber-300" />
              </span>
              <div className="text-left">
                <span className="text-xs font-bold text-white block">
                  AI What-If Decision Assistant
                </span>
                <span className="text-[10px] text-white/60">
                  Ask simulation questions & test crowd outcomes
                </span>
              </div>
            </div>
            {showWhatIf ? (
              <ChevronUp className="w-4 h-4 text-blue-400" />
            ) : (
              <ChevronDown className="w-4 h-4 text-blue-400" />
            )}
          </button>

          {showWhatIf && (
            <div className="animate-in fade-in zoom-in-98 duration-200">
              <WhatIfAssistant
                zones={zones}
                gates={gates}
                transports={transports}
                onSimulate={(actionId) => onSimulateAction(actionId || 'action-1')}
              />
            </div>
          )}
        </div>
      )}

      <div className="flex flex-col gap-4 mt-1">
        {actions.map((action, idx) => {
          const isApplied = action.status === 'applied';

          return (
            <div
              key={action.id}
              id={`action-card-${action.id}`}
              className={`p-5 rounded-2xl border backdrop-blur-xl transition-all shadow-xl ${
                isApplied
                  ? 'bg-black/60 border-emerald-500/40 shadow-[0_0_20px_rgba(16,185,129,0.15)]'
                  : idx === 0
                  ? 'bg-black/60 border-blue-500/40 shadow-[0_0_25px_rgba(59,130,246,0.15)]'
                  : 'bg-black/60 border-white/10'
              }`}
            >
              {/* Badge row */}
              <div className="flex items-center justify-between">
                <span
                  className={`text-[10px] font-extrabold uppercase px-2.5 py-0.5 rounded-full tracking-wider ${
                    isApplied
                      ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                      : idx === 0
                      ? 'bg-blue-600/20 text-blue-400 border border-blue-500/30'
                      : 'bg-white/5 text-white/60 border border-white/10'
                  }`}
                >
                  {isApplied ? 'Applied to Mesh' : 'Recommended'}
                </span>
                <span className="text-xs font-mono text-blue-400 font-bold">
                  {action.confidence}% Confidence
                </span>
              </div>

              {/* Title & Description */}
              <div className="mt-3">
                <h3 className="text-base font-bold text-white leading-snug">
                  {action.title}
                </h3>
                <p className="text-xs text-white/70 mt-1 leading-relaxed">
                  {action.description}
                </p>
              </div>

              {/* Impact Metric Grid */}
              <div className="grid grid-cols-2 gap-2 my-3.5 p-3 bg-white/5 rounded-xl border border-white/10 backdrop-blur-md">
                <div className="flex flex-col">
                  <span className="text-[11px] text-white/40 font-bold uppercase tracking-wider">Pressure</span>
                  <div className="flex items-center gap-1.5 mt-1">
                    <TrendingDown className="w-4 h-4 text-emerald-400" />
                    <span className="text-sm font-bold font-mono text-emerald-400">
                      94% → 71%
                    </span>
                  </div>
                </div>

                <div className="flex flex-col border-l border-white/10 pl-3">
                  <span className="text-[11px] text-white/40 font-bold uppercase tracking-wider">Queue</span>
                  <div className="flex items-center gap-1.5 mt-1">
                    <Clock className="w-4 h-4 text-blue-400" />
                    <span className="text-sm font-bold font-mono text-blue-300">
                      28m → 8m
                    </span>
                  </div>
                </div>
              </div>

              {/* Button Row */}
              <div className="flex items-center gap-2.5 pt-1">
                <button
                  id={`btn-simulate-action-${action.id}`}
                  onClick={() => onSimulateAction(action.id)}
                  disabled={isApplied}
                  className={`flex-1 py-3.5 px-3 rounded-xl text-xs font-bold tracking-wide shadow-lg transition active:scale-95 flex items-center justify-center gap-1.5 min-h-[46px] ${
                    isApplied
                      ? 'bg-emerald-900/40 text-emerald-300 border border-emerald-500/40 cursor-default'
                      : 'bg-blue-600 hover:bg-blue-500 text-white shadow-blue-600/30'
                  }`}
                >
                  <span>{isApplied ? 'INTERVENTION COMMITTED' : 'SIMULATE INTERVENTION'}</span>
                  {!isApplied && <ArrowRight className="w-3.5 h-3.5" />}
                </button>

                <button
                  id={`btn-why-action-${action.id}`}
                  onClick={() => setActiveWhyAction(action)}
                  className="py-3.5 px-3.5 rounded-xl text-xs font-bold bg-white/5 hover:bg-white/10 text-white/80 border border-white/10 transition active:scale-95 flex items-center justify-center gap-1.5 min-h-[46px]"
                >
                  <HelpCircle className="w-3.5 h-3.5 text-blue-400" />
                  <span>WHY?</span>
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {/* WHY Modal */}
      {activeWhyAction && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md">
          <div className="bg-black/80 backdrop-blur-2xl rounded-3xl border border-white/10 p-6 w-full max-w-sm shadow-2xl animate-in zoom-in-95">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2 text-blue-400 font-bold text-sm">
                <BrainCircuit className="w-4 h-4" />
                Algorithmic Rationale
              </div>
              <button
                onClick={() => setActiveWhyAction(null)}
                className="p-1.5 rounded-full bg-white/5 text-white/50 hover:text-white border border-white/10"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <h4 className="text-sm font-bold text-white mb-2">
              {activeWhyAction.title}
            </h4>

            <p className="text-xs text-white/80 leading-relaxed bg-white/5 p-3 rounded-2xl border border-white/10">
              {activeWhyAction.whyExplanation}
            </p>

            <div className="mt-3 p-3 bg-blue-600/10 rounded-2xl border border-blue-500/20 text-[11px] text-white/70 flex flex-col gap-1.5">
              <div className="flex justify-between">
                <span className="text-white/40">Prediction Engine:</span>
                <span className="font-mono text-blue-300">XGBoost Gradient Regressor</span>
              </div>
              <div className="flex justify-between">
                <span className="text-white/40">Optimization:</span>
                <span className="font-mono text-purple-300">OR-Tools Max-Flow</span>
              </div>
              <div className="flex justify-between">
                <span className="text-white/40">Predicted Bottleneck Relief:</span>
                <span className="font-mono text-emerald-300">−23% within 12 min</span>
              </div>
            </div>

            <button
              onClick={() => {
                const actionId = activeWhyAction.id;
                setActiveWhyAction(null);
                onSimulateAction(actionId);
              }}
              className="w-full mt-4 py-3 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-bold shadow-lg shadow-blue-600/30 transition active:scale-95"
            >
              Simulate This Intervention
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
